name: gym_manager_backup_manager_core
description: A core library for managing backups in the Gym Manager application.
version: 1.0.0
publish_to: none # Remove this line if you wish to publish to pub.dev
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  dio: ^5.4.3+1
  uuid: ^3.0.6
  gym_manager_core:
    git:
      url: https://github.com/Wired-shop/gym_manager_core.git
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
